//! Core memory trait and types that the store layer depends on.
//!
//! These will be moved here fully once the `memory/` domain is extracted.
//! For now they provide the minimal interface `memory_store` needs.

use serde::{Deserialize, Serialize};

/// Taint tracking for memory entries — distinguishes user-authored content
/// from externally-synced content that should not trigger tool execution.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryTaint {
    /// Content authored by the user or generated by the agent.
    Internal,
    /// Content ingested from external sources (Gmail, Slack, Notion, etc.).
    ExternalSync,
}

impl MemoryTaint {
    pub fn as_db_str(&self) -> &'static str {
        match self {
            Self::Internal => "internal",
            Self::ExternalSync => "external_sync",
        }
    }

    pub fn from_db_str(s: &str) -> Self {
        match s {
            "external_sync" => Self::ExternalSync,
            _ => Self::Internal,
        }
    }
}

impl Default for MemoryTaint {
    fn default() -> Self {
        Self::Internal
    }
}

/// Placeholder Memory trait (the real one lives in orchestration::traits when __full_app).
#[cfg(feature = "__full_app")]
pub use crate::orchestration::traits::Memory;

/// Ingestion queue placeholder.
pub mod ingestion {
    /// Queue control for ingestion (stub).
    pub mod queue {
        pub fn pause() {}
        pub fn resume() {}
        pub fn is_paused() -> bool { false }
    }
}
