//! Core memory trait and types that the store layer depends on.
//!
//! These will be moved here fully once the `memory/` domain is extracted.
//! For now they provide the minimal interface `memory_store` needs.

use serde::{Deserialize, Serialize};

/// Taint tracking for memory entries — distinguishes user-authored content
/// from externally-synced content that should not trigger tool execution.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MemoryTaint {
    /// Content authored by the user or generated by the agent.
    Internal,
    /// Content ingested from external sources (Gmail, Slack, Notion, etc.).
    ExternalSync,
}

impl MemoryTaint {
    pub fn as_db_str(&self) -> &'static str {
        match self {
            Self::Internal => "internal",
            Self::ExternalSync => "external_sync",
        }
    }

    pub fn from_db_str(s: &str) -> Self {
        match s {
            "external_sync" => Self::ExternalSync,
            _ => Self::Internal,
        }
    }
}

impl Default for MemoryTaint {
    fn default() -> Self {
        Self::Internal
    }
}

/// Re-export Memory and related traits from orchestration when available.
#[cfg(feature = "__full_app")]
pub use crate::orchestration::traits::{Memory, MemoryCategory, MemoryEntry, NamespaceSummary, RecallOpts};

/// Ingestion types and queue control.
pub mod ingestion {
    use serde::{Deserialize, Serialize};

    /// Ingestion job state.
    #[derive(Clone, Debug, Default, Serialize, Deserialize)]
    pub enum IngestionState {
        #[default]
        Idle,
        Running,
        Completed,
        Failed(String),
    }

    /// Ingestion job descriptor.
    #[derive(Clone, Debug, Default)]
    pub struct IngestionJob {
        pub id: String,
        pub source: String,
        pub state: IngestionState,
    }

    /// Ingestion queue handle.
    #[derive(Clone, Debug, Default)]
    pub struct IngestionQueue;

    /// Ingestion config.
    #[derive(Clone, Debug, Default, Serialize, Deserialize)]
    pub struct MemoryIngestionConfig {
        pub enabled: bool,
    }

    /// Ingestion request.
    #[derive(Clone, Debug)]
    pub struct MemoryIngestionRequest {
        pub source: String,
        pub content: String,
    }

    /// Ingestion result.
    #[derive(Clone, Debug, Default)]
    pub struct MemoryIngestionResult {
        pub chunks_created: u32,
    }

    /// Queue control submodule.
    pub mod queue {
        pub fn pause() {}
        pub fn resume() {}
        pub fn is_paused() -> bool { false }
        pub fn start_worker_with_state(_config: &crate::config::Config) {}
    }

    pub fn pause() {}
    pub fn resume() {}
    pub fn is_paused() -> bool { false }
    pub fn start_worker_with_state(_config: &crate::config::Config) {}
}
